dataDir: data
patterns:
  prerequisites:
    - pd.read_csv(deba.data(r'.+\.csv'))
  references:
    - files_meta_frame(r'.+\.dvc')
  targets:
    - "`*`.to_csv(deba.data(r'.+\\.csv'))"
stages:
  - name: meta
  - name: ocr
    commonPrerequisites:
      - ocr_results
  - name: ner
  - name: clean
    ignoredTargets:
      - duplicates.csv
  - name: match
  - name: fuse
    ignoredTargets:
      - duplicates.csv
      - fuse/person.csv
    commonPrerequisites:
      - datavalid.yml
  - name: analysis
  - name: consolidate
targets:
  - consolidate/personnel.csv
  - consolidate/allegation.csv
  - consolidate/use_of_force.csv
  - consolidate/stop_and_search.csv
  - consolidate/appeals.csv
  - consolidate/event.csv
  - analysis/coaccusals.csv
